=== bily/mapsforge/mapsforge/src/org/mapsforge/preprocessing/map/osmosis/tag-mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://mapsforge.org/tag-mapping" xmlns:tns="http://mapsforge.org/tag-mapping" elementFormDefault="qualified">



    <complexType name="osm-tag">
    	<attribute name="key" use="required" default="highway">
    		<simpleType>
    			<restriction base="string">
    				<minLength value="1"></minLength>
    				<maxLength value="100"></maxLength>
    				<whiteSpace value="collapse"></whiteSpace>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="value" use="required">
    		<simpleType>
    			<restriction base="string">
    				<maxLength value="100"></maxLength>
    				<minLength value="1"></minLength>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="zoom-appear" use="optional" default="17">
    		<simpleType>
    			<restriction base="int">
    				<minInclusive value="0"></minInclusive>
    				<maxInclusive value="21"></maxInclusive>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="enabled" type="boolean" use="optional" default="false"></attribute>
    	<attribute name="renderable" type="boolean" use="optional" default="false"></attribute>
    </complexType>
    
    <complexType name="tag-group">
    	<sequence>
    		<element name="osm-tag" type="tns:osm-tag"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="enabled" type="boolean" use="optional" default="false"></attribute>
    </complexType>
    



    <complexType name="tag-mapping">
    	<sequence>
    		<element name="pois" type="tns:tag-group"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="ways" type="tns:tag-group"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="default-zoom-appear" default="17" use="required">
    		<simpleType>
    			<restriction base="int">
    				<minInclusive value="0"></minInclusive>
    				<maxInclusive value="21"></maxInclusive>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="profile-name" use="required">
    		<simpleType>
    			<restriction base="string">
    				<minLength value="3"></minLength>
    				<maxLength value="100"></maxLength>
    				<whiteSpace value="collapse"></whiteSpace>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <element name="tag-mapping" type="tns:tag-mapping"></element>
</schema>

=== bily/mapsforge/mapsforge/src/org/mapsforge/preprocessing/map/osmosis/tag-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<tag-mapping xmlns="http://mapsforge.org/tag-mapping"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://mapsforge.org/tag-mapping tag-mapping.xsd "
	default-zoom-appear="16" profile-name="default-profile">

	<!-- ************* POIS *************** -->

	<!-- HIGHWAY TAGS -->
	<pois>
		<osm-tag key="highway" value="bus_stop" zoom-appear="16" />
		<osm-tag key="highway" value="mini_roundabout" zoom-appear="17" />
		<osm-tag key="highway" value="traffic_signals" zoom-appear="17" />
		<osm-tag key="highway" value="turning_circle" zoom-appear="17" />
	</pois>

	<!-- PUBLIC AMENITIES -->
	<pois>
		<osm-tag key="amenity" value="atm" zoom-appear="17" />
		<osm-tag key="amenity" value="bank" zoom-appear="17" />
		<osm-tag key="amenity" value="bicycle_rental" zoom-appear="17" />
		<osm-tag key="amenity" value="bus_station" zoom-appear="16" />
		<osm-tag key="amenity" value="cafe" zoom-appear="17" />
		<osm-tag key="amenity" value="cinema" zoom-appear="17" />
		<osm-tag key="amenity" value="fast_food" zoom-appear="17" />
		<osm-tag key="amenity" value="fountain" zoom-appear="16" />
		<osm-tag key="amenity" value="fire_station" zoom-appear="17" />
		<osm-tag key="amenity" value="fuel" zoom-appear="17" />
		<osm-tag key="amenity" value="hospital" zoom-appear="16" />
		<osm-tag key="amenity" value="library" zoom-appear="17" />
		<osm-tag key="amenity" value="parking" zoom-appear="17" />
		<osm-tag key="amenity" value="pharmacy" zoom-appear="17" />
		<osm-tag key="amenity" value="place_of_worship" zoom-appear="17" />
		<osm-tag key="amenity" value="police" zoom-appear="17" />
		<osm-tag key="amenity" value="post_box" zoom-appear="17" />
		<osm-tag key="amenity" value="post_office" zoom-appear="17" />
		<osm-tag key="amenity" value="pub" zoom-appear="17" />
		<osm-tag key="amenity" value="recycling" zoom-appear="17" />
		<osm-tag key="amenity" value="restaurant" zoom-appear="17" />
		<osm-tag key="amenity" value="school" zoom-appear="17" />
		<osm-tag key="amenity" value="shelter" zoom-appear="16" />
		<osm-tag key="amenity" value="telephone" zoom-appear="17" />
		<osm-tag key="amenity" value="theatre" zoom-appear="17" />
		<osm-tag key="amenity" value="toilets" zoom-appear="17" />
		<osm-tag key="amenity" value="university" zoom-appear="17" />

		<osm-tag key="shop" value="bakery" zoom-appear="17" />
		<osm-tag key="shop" value="hairdresser" zoom-appear="17" />
		<osm-tag key="shop" value="organic" zoom-appear="17" />
		<osm-tag key="shop" value="supermarket" zoom-appear="17" />

		<osm-tag key="leisure" value="playground" zoom-appear="17" />
		<osm-tag key="leisure" value="slipway" zoom-appear="17" />

		<osm-tag key="emergency" value="phone" zoom-appear="17" />
	</pois>

	<!-- PUBLIC TRANSPORT TAGS -->
	<pois>
		<osm-tag key="railway" value="halt" zoom-appear="17" />
		<osm-tag key="railway" value="level_crossing" zoom-appear="16" />
		<osm-tag key="railway" value="station" zoom-appear="15" />
		<osm-tag key="railway" value="tram_stop" zoom-appear="17" />

		<osm-tag key="station" value="light_rail" zoom-appear="17" />
		<osm-tag key="station" value="subway" zoom-appear="17" />
	</pois>

	<!-- TOURISM TAGS -->
	<pois>
		<osm-tag key="tourism" value="attraction" zoom-appear="17" />
		<osm-tag key="tourism" value="hostel" zoom-appear="17" />
		<osm-tag key="tourism" value="hotel" zoom-appear="17" />
		<osm-tag key="tourism" value="information" zoom-appear="17" />
		<osm-tag key="tourism" value="museum" zoom-appear="17" />
		<osm-tag key="tourism" value="viewpoint" zoom-appear="15" />

		<osm-tag key="historic" value="memorial" zoom-appear="17" />
		<osm-tag key="historic" value="monument" zoom-appear="17" />
	</pois>

	<!-- PLACES TAGS -->
	<pois>
		<osm-tag key="place" value="city" zoom-appear="6" />
		<osm-tag key="place" value="country" zoom-appear="3" />
		<osm-tag key="place" value="island" zoom-appear="12" />
		<osm-tag key="place" value="suburb" zoom-appear="12" />
		<osm-tag key="place" value="town" zoom-appear="9" />
		<osm-tag key="place" value="village" zoom-appear="12" />
	</pois>

	<!-- NATURAL TAGS -->
	<pois>
		<osm-tag key="natural" value="cave_entrance" zoom-appear="14" />
		<osm-tag key="natural" value="peak" zoom-appear="15" />
		<osm-tag key="natural" value="spring" zoom-appear="17" />
		<osm-tag key="natural" value="tree" zoom-appear="17" />
		<osm-tag key="natural" value="volcano" zoom-appear="12" />
	</pois>

	<!-- OTHER POIS -->
	<pois>
		<osm-tag key="barrier" value="bollard" zoom-appear="16" />
		<osm-tag key="barrier" value="cycle_barrier" zoom-appear="17" />
		<osm-tag key="man_made" value="lighthouse" zoom-appear="17" />
		<osm-tag key="man_made" value="surveillance" zoom-appear="17" />
		<osm-tag key="man_made" value="tower" zoom-appear="17" />
		<osm-tag key="man_made" value="windmill" zoom-appear="17" />
		<osm-tag key="power" value="generator" zoom-appear="17" />
		<osm-tag key="power" value="tower" zoom-appear="17" />
	</pois>

	<!-- AIRPORT TAGS -->
	<pois>
		<osm-tag key="aeroway" value="aerodrome" zoom-appear="13" />
		<osm-tag key="aeroway" value="gate" zoom-appear="17" />
		<osm-tag key="aeroway" value="helipad" zoom-appear="17" />
	</pois>



	<!-- ************* WAYS *************** -->

	<!-- HIGHWAY TAGS -->
	<ways>
		<osm-tag key="highway" value="bridleway" zoom-appear="13" />
		<osm-tag key="highway" value="bus_guideway" zoom-appear="14" />
		<osm-tag key="highway" value="construction" zoom-appear="15" />
		<osm-tag key="highway" value="cycleway" zoom-appear="13" />
		<osm-tag key="highway" value="footway" zoom-appear="15" />
		<osm-tag key="highway" value="living_street" zoom-appear="14" />
		<osm-tag key="highway" value="motorway" zoom-appear="6" />
		<osm-tag key="highway" value="motorway_link" zoom-appear="6" />
		<osm-tag key="highway" value="path" zoom-appear="14" />
		<osm-tag key="highway" value="pedestrian" zoom-appear="14" />
		<osm-tag key="highway" value="primary" zoom-appear="8" />
		<osm-tag key="highway" value="primary_link" zoom-appear="8" />
		<osm-tag key="highway" value="raceway" zoom-appear="13" />
		<osm-tag key="highway" value="residential" zoom-appear="14" />
		<osm-tag key="highway" value="road" zoom-appear="12" />
		<osm-tag key="highway" value="secondary" zoom-appear="9" />
		<osm-tag key="highway" value="secondary_link" zoom-appear="9" />
		<osm-tag key="highway" value="service" zoom-appear="14" />
		<osm-tag key="highway" value="services" zoom-appear="14" />
		<osm-tag key="highway" value="steps" zoom-appear="16" />
		<osm-tag key="highway" value="tertiary" zoom-appear="10" />
		<osm-tag key="highway" value="track" zoom-appear="12" />
		<osm-tag key="highway" value="trunk" zoom-appear="6" />
		<osm-tag key="highway" value="trunk_link" zoom-appear="6" />
		<osm-tag key="highway" value="unclassified" zoom-appear="13" />
	</ways>

	<!-- NATURAL / WATERWAY TAGS -->
	<ways>
		<osm-tag key="natural" value="beach" zoom-appear="14" />
		<osm-tag key="natural" value="coastline" zoom-appear="0" />
		<osm-tag key="natural" value="glacier" zoom-appear="8" />
		<osm-tag key="natural" value="heath" zoom-appear="12" />
		<osm-tag key="natural" value="land" zoom-appear="12" />
		<osm-tag key="natural" value="scrub" zoom-appear="12" />
		<osm-tag key="natural" value="water" zoom-appear="12" />
		<osm-tag key="natural" value="wood" zoom-appear="12" />

		<osm-tag key="waterway" value="canal" zoom-appear="9" />
		<osm-tag key="waterway" value="dam" zoom-appear="12" />
		<osm-tag key="waterway" value="drain" zoom-appear="12" />
		<osm-tag key="waterway" value="river" zoom-appear="8" />
		<osm-tag key="waterway" value="riverbank" zoom-appear="8" />
		<osm-tag key="waterway" value="stream" zoom-appear="6" />
	</ways>

	<!-- LANDUSE TAGS -->
	<ways>
		<osm-tag key="landuse" value="allotments" zoom-appear="12" />
		<osm-tag key="landuse" value="basin" zoom-appear="14" />
		<osm-tag key="landuse" value="brownfield" zoom-appear="12" />
		<osm-tag key="landuse" value="cemetery" zoom-appear="12" />
		<osm-tag key="landuse" value="commercial" zoom-appear="12" />
		<osm-tag key="landuse" value="construction" zoom-appear="14" />
		<osm-tag key="landuse" value="farm" zoom-appear="12" />
		<osm-tag key="landuse" value="farmland" zoom-appear="12" />
		<osm-tag key="landuse" value="forest" zoom-appear="12" />
		<osm-tag key="landuse" value="grass" zoom-appear="12" />
		<osm-tag key="landuse" value="greenfield" zoom-appear="12" />
		<osm-tag key="landuse" value="industrial" zoom-appear="12" />
		<osm-tag key="landuse" value="military" zoom-appear="12" />
		<osm-tag key="landuse" value="quarry" zoom-appear="12" />
		<osm-tag key="landuse" value="railway" zoom-appear="12" />
		<osm-tag key="landuse" value="recreation_ground" zoom-appear="12" />
		<osm-tag key="landuse" value="reservoir" zoom-appear="12" />
		<osm-tag key="landuse" value="residential" zoom-appear="12" />
		<osm-tag key="landuse" value="retail" zoom-appear="12" />
		<osm-tag key="landuse" value="village_green" zoom-appear="12" />
		<osm-tag key="landuse" value="vineyard" zoom-appear="12" />
		<osm-tag key="landuse" value="wood" zoom-appear="12" />
	</ways>

	<!-- LEISURE/SPORT TAGS -->
	<ways>
		<osm-tag key="leisure" value="common" zoom-appear="12" />
		<osm-tag key="leisure" value="garden" zoom-appear="12" />
		<osm-tag key="leisure" value="golf_course" zoom-appear="12" />
		<osm-tag key="leisure" value="park" zoom-appear="12" />
		<osm-tag key="leisure" value="pitch" zoom-appear="15" />
		<osm-tag key="leisure" value="playground" zoom-appear="16" />
		<osm-tag key="leisure" value="sports_centre" zoom-appear="12" />
		<osm-tag key="leisure" value="stadium" zoom-appear="12" />
		<osm-tag key="leisure" value="track" zoom-appear="15" />
		<osm-tag key="leisure" value="water_park" zoom-appear="15" />

		<osm-tag key="sport" value="golf" zoom-appear="15" />
		<osm-tag key="sport" value="shooting" zoom-appear="15" />
