=== bily/mapsforge/mapsforge/src/org/mapsforge/preprocessing/automization/mapsforge-preprocessing-conf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://mapsforge.org/mapsforge-preprocessing-conf"
	elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://mapsforge.org/mapsforge-preprocessing-conf">

	<xsd:element name="configuration" type="configuration"></xsd:element>
	<xsd:element name="source" type="source" abstract="true"></xsd:element>
	<xsd:element name="read-pbf" type="read-pbf" substitutionGroup="source"></xsd:element>
	<xsd:element name="sink-source" type="sink-source" abstract="true"></xsd:element>
	<xsd:element name="bbox-area-filter" type="bbox-area-filter" substitutionGroup="sink-source"></xsd:element>
	<xsd:element name="polygon-area-filter" type="polygon-area-filter" substitutionGroup="sink-source"></xsd:element>
	<xsd:element name="sink" type="sink" abstract="true"></xsd:element>
	<xsd:element name="write-pbf" type="write-pbf" substitutionGroup="sink"></xsd:element>
	<xsd:element name="mapfile-writer" type="mapfile-writer" substitutionGroup="sink"></xsd:element>
	<xsd:element name="routinggraph-writer" type="routinggraph-writer" substitutionGroup="sink"></xsd:element>

	<xsd:simpleType name="latitude">
		<xsd:restriction base="xsd:double">
			<xsd:minInclusive value="-90"></xsd:minInclusive>
			<xsd:maxInclusive value="90"></xsd:maxInclusive>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="longitude">
		<xsd:restriction base="xsd:double">
			<xsd:minInclusive value="-180"></xsd:minInclusive>
			<xsd:maxInclusive value="180"></xsd:maxInclusive>
		</xsd:restriction>
	</xsd:simpleType>
	
	<xsd:complexType name="configuration">
		<xsd:sequence>
			<xsd:element name="pipeline" type="pipeline" minOccurs="1" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
        <xsd:attribute name="osmosis-home" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="working-dir" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="output-dir" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="logging-dir" type="xsd:string" use="required"></xsd:attribute>
        <xsd:attribute name="destination-dir" type="xsd:string" use="optional"></xsd:attribute>
    	<xsd:attribute name="move" type="xsd:boolean" default="false" use="optional"></xsd:attribute>
    </xsd:complexType>
	
	<xsd:complexType name="pipeline">
		<xsd:sequence>
			<xsd:element ref="source" maxOccurs="1" minOccurs="1"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="output-dir" type="xsd:string" use="optional"></xsd:attribute>
		<xsd:attribute name="logging-level" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="FINE"></xsd:enumeration>
					<xsd:enumeration value="FINER"></xsd:enumeration>
					<xsd:enumeration value="FINEST"></xsd:enumeration>
					<xsd:enumeration value="INFO"></xsd:enumeration>
					<xsd:enumeration value="SEVERE"></xsd:enumeration>
					<xsd:enumeration value="WARNING"></xsd:enumeration>
					<xsd:enumeration value="ALL"></xsd:enumeration>
					<xsd:enumeration value="OFF"></xsd:enumeration>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="source" abstract="true">
		<xsd:sequence minOccurs="1">
			<xsd:element ref="sink-source" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			<xsd:element ref="sink" minOccurs="0" maxOccurs="unbounded"></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="file" type="xsd:string" use="required"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="read-pbf">
		<xsd:complexContent>
			<xsd:extension base="source"></xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="sink-source" abstract="true">
		<xsd:sequence minOccurs="1">
			<xsd:element ref="sink-source" minOccurs="0" maxOccurs="unbounded"> </xsd:element>
			<xsd:element ref="sink" minOccurs="0" maxOccurs="unbounded" ></xsd:element>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="optional"></xsd:attribute>
	</xsd:complexType>
	
	<xsd:complexType name="bbox-area-filter">
		<xsd:complexContent>
			<xsd:extension base="sink-source">
				<xsd:attribute name="minlat" type="latitude" use="required"></xsd:attribute>
				<xsd:attribute name="minlon" type="longitude" use="required"></xsd:attribute>
				<xsd:attribute name="maxlat" type="latitude" use="required"></xsd:attribute>
				<xsd:attribute name="maxlon" type="longitude" use="required"></xsd:attribute>
				<xsd:attribute name="completeWays" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
				<xsd:attribute name="completeRelations" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
				<xsd:attribute name="clipIncompleteEntities" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="polygon-area-filter">
		<xsd:complexContent>
			<xsd:extension base="sink-source">
				<xsd:attribute name="polygon-file" type="xsd:string" use="required"></xsd:attribute>
				<xsd:attribute name="completeWays" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
				<xsd:attribute name="completeRelations" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
				<xsd:attribute name="clipIncompleteEntities" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="sink" abstract="true">
		<xsd:attribute name="file" type="xsd:string" use="required"></xsd:attribute>
		<xsd:attribute name="md5" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="write-pbf">
		<xsd:complexContent>
			<xsd:extension base="sink">
				<xsd:attribute name="omit-metadata" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
				<xsd:attribute name="compress" use="optional" default="none">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="none"></xsd:enumeration>
							<xsd:enumeration value="deflate"></xsd:enumeration>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	
	<xsd:complexType name="mapfile-writer">
		<xsd:complexContent>
			<xsd:extension base="sink">
				<xsd:attribute name="type" use="optional" default="ram">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:enumeration value="ram"></xsd:enumeration>
							<xsd:enumeration value="hd"></xsd:enumeration>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="bbox" use="optional">
					<xsd:simpleType>
						<xsd:restriction base="xsd:string">
							<xsd:whiteSpace value="collapse"></xsd:whiteSpace>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="map-start-position" type="xsd:string" use="optional"></xsd:attribute>
				<xsd:attribute name="comment" type="xsd:string" use="optional"></xsd:attribute>
				<xsd:attribute name="waynode-compression" type="xsd:boolean" use="optional" default="true"></xsd:attribute>
				<xsd:attribute name="pixel-filter" type="xsd:boolean" default="true" use="optional"></xsd:attribute>
				<xsd:attribute name="polygon-clipping" type="xsd:boolean" use="optional" default="true"></xsd:attribute>
				<xsd:attribute name="zoom-interval-conf" type="xsd:string" use="optional" default="8,0,11,14,12,21"></xsd:attribute>
				<xsd:attribute name="thread-pool-size" use="optional">
					<xsd:simpleType>
						<xsd:restriction base="xsd:int">
							<xsd:minInclusive value="1"></xsd:minInclusive>
							<xsd:maxInclusive value="128"></xsd:maxInclusive>
						</xsd:restriction>
					</xsd:simpleType>
				</xsd:attribute>
				<xsd:attribute name="debug-file" type="xsd:boolean" use="optional" default="false"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:complexType name="routinggraph-writer">
		<xsd:complexContent>
			<xsd:extension base="sink">
				<xsd:attribute name="way-types" type="xsd:string" use="optional"></xsd:attribute>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

</xsd:schema>

=== bily/mapsforge/mapsforge/src/org/mapsforge/preprocessing/automization/mapsforge-preprocessing-conf.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration 
	osmosis-home="/export/local-1/public/mapsforge/osmosis-0.38"
	working-dir="/export/local-1/public/mapsforge/mkunis"
	logging-dir="logs" 
	output-dir="out"
	destination-dir="/web/ftp.mapsforge.org/public"  
	xmlns="http://mapsforge.org/mapsforge-preprocessing-conf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mapsforge.org/mapsforge-preprocessing-conf mapsforge-preprocessing-conf.xsd ">
  <pipeline name="germany.pbf" output-dir="europe">
    <read-pbf file="files/planet.osm.pbf">
    	<bbox-area-filter maxlat="55.789" minlat="46.624" maxlon="16.432" minlon="4.262" clipIncompleteEntities="true">
    		<polygon-area-filter polygon-file="polygons/germany_simple.poly" clipIncompleteEntities="true">
    			<write-pbf file="germany.osm.pbf" omit-metadata="false" compress="deflate" md5="true"/>
    		</polygon-area-filter>	
    	</bbox-area-filter>
    </read-pbf>
  </pipeline>
  <pipeline name="germany.map" output-dir="europe" >
  	<read-pbf file="out/europe/germany.osm.pbf">
  		<mapfile-writer file="germany-0.2.2.map" type="hd" map-start-position="52.518682,13.376123" md5="true"/>
  	</read-pbf>
  </pipeline>
  <pipeline name="baden-wuerttemberg.map" output-dir="maps/europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/baden-wuerttemberg.poly" clipIncompleteEntities="true">
			<mapfile-writer file="baden-wuerttemberg-0.2.2.map" type="ram" map-start-position="48.784092,9.181652" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="bayern.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/bayern.poly" clipIncompleteEntities="true">
			<mapfile-writer file="bayern-0.2.2.map" type="ram" map-start-position="48.140203,11.558347" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="berlin.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/berlin.poly" clipIncompleteEntities="true">
			<mapfile-writer file="berlin-0.2.2.map" type="ram" map-start-position="52.525582,13.370061" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="brandenburg.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/brandenburg.poly" clipIncompleteEntities="true">
			<mapfile-writer file="brandenburg-0.2.2.map" type="ram" map-start-position="52.391486,13.06622" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="bremen.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/bremen.poly" clipIncompleteEntities="true">
			<mapfile-writer file="bremen-0.2.2.map" type="ram" map-start-position="53.083444,8.813782" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="hamburg.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/hamburg.poly" clipIncompleteEntities="true">
			<mapfile-writer file="hamburg-0.2.2.map" type="ram" map-start-position="53.553223,10.007021" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="hessen.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/hessen.poly" clipIncompleteEntities="true">
			<mapfile-writer file="hessen-0.2.2.map" type="ram" map-start-position="50.070748,8.243759" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="mecklenburg-vorpommern.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/mecklenburg-vorpommern.poly" clipIncompleteEntities="true">
			<mapfile-writer file="mecklenburg-vorpommern-0.2.2.map" type="ram" map-start-position="53.634397,11.407306" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="niedersachsen.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/niedersachsen.poly" clipIncompleteEntities="true">
			<mapfile-writer file="niedersachsen-0.2.2.map" type="ram" map-start-position="52.377014,9.741676" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="nordrhein-westfalen.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/nordrhein-westfalen.poly" clipIncompleteEntities="true">
			<mapfile-writer file="nordrhein-westfalen-0.2.2.map" type="ram" map-start-position="51.219707,6.794465" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="rheinland-pfalz.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/rheinland-pfalz.poly" clipIncompleteEntities="true">
			<mapfile-writer file="rheinland-pfalz-0.2.2.map" type="ram" map-start-position="50.001105,8.258736" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="saarland.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/saarland.poly" clipIncompleteEntities="true">
			<mapfile-writer file="saarland-0.2.2.map" type="ram" map-start-position="49.241166,6.990352" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="sachsen-anhalt.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/sachsen-anhalt.poly" clipIncompleteEntities="true">
			<mapfile-writer file="sachsen-anhalt-0.2.2.map" type="ram" map-start-position="52.130669,11.628792" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="sachsen.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/sachsen.poly" clipIncompleteEntities="true">
			<mapfile-writer file="sachsen-0.2.2.map" type="ram" map-start-position="51.040557,13.731966" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="schleswig-holstein.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/schleswig-holstein.poly" clipIncompleteEntities="true">
			<mapfile-writer file="schleswig-holstein-0.2.2.map" type="ram" map-start-position="54.314971,10.13190" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
   <pipeline name="thueringen.map" output-dir="europe/germany">
	<read-pbf file="out/europe/germany.osm.pbf">
		<polygon-area-filter polygon-file="polygons/thueringen.poly" clipIncompleteEntities="true">
			<mapfile-writer file="thueringen-0.2.2.map" type="ram" map-start-position="50.972535,11.038556" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
</configuration>

=== bily/mapsforge/mapsforge-map-writer-automatization/src/main/config/mapsforge-preprocessing-conf-other-europe.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration 
	osmosis-home="/export/local-1/public/mapsforge/preprocessing/bin/osmosis-0.39"
	working-dir="/export/local-1/public/mapsforge/preprocessing"
	logging-dir="log" 
	output-dir="output"
	destination-dir="/web/ftp.mapsforge.org/public"
	move="false"  
	xmlns="http://mapsforge.org/mapsforge-preprocessing-conf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mapsforge.org/mapsforge-preprocessing-conf mapsforge-preprocessing-conf.xsd ">


<!-- MAP FILES -->

  <pipeline name="poland.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/poland.poly" clipIncompleteEntities="true">
			<mapfile-writer file="poland-0.2.4.map" type="hd" map-start-position="52.230073,21.011395" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="czech_republic.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/czech_republic.poly" clipIncompleteEntities="true">
			<mapfile-writer file="czech_republic-0.2.4.map" type="hd" map-start-position="50.087699,14.419212" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="slovakia.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/slovakia.poly" clipIncompleteEntities="true">
			<mapfile-writer file="slovakia-0.2.4.map" type="hd" map-start-position="48.14805,17.108459" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="hungary.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/hungary.poly" clipIncompleteEntities="true">
			<mapfile-writer file="hungary-0.2.4.map" type="ram" map-start-position="47.498532,19.040766" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="croatia.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/croatia.poly" clipIncompleteEntities="true">
			<mapfile-writer file="croatia-0.2.4.map" type="ram" map-start-position="45.814713,15.978413" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="serbia.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/serbia.poly" clipIncompleteEntities="true">
			<mapfile-writer file="serbia-0.2.4.map" type="ram" map-start-position="44.802575,20.465684" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="slovenia.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/slovenia.poly" clipIncompleteEntities="true">
			<mapfile-writer file="slovenia-0.2.4.map" type="ram" map-start-position="46.051493,14.505944" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="bosnia-herzegovina.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/bosnia-herzegovina.poly" clipIncompleteEntities="true">
			<mapfile-writer file="bosnia-herzegovina-0.2.4.map" type="ram" map-start-position="43.847403,18.357124" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="montenegro.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/montenegro.poly" clipIncompleteEntities="true">
			<mapfile-writer file="montenegro-0.2.4.map" type="ram" map-start-position="42.439516,19.266071" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="albania.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/albania.poly" clipIncompleteEntities="true">
			<mapfile-writer file="albania-0.2.4.map" type="ram" map-start-position="41.326198,19.81601" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="kosovo.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/kosovo.poly" clipIncompleteEntities="true">
			<mapfile-writer file="kosovo-0.2.4.map" type="ram" map-start-position="42.657965,21.153831" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="macedonia.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/macedonia.poly" clipIncompleteEntities="true">
			<mapfile-writer file="macedonia-0.2.4.map" type="ram" map-start-position="41.991235,21.446857" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="greece.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/greece.poly" clipIncompleteEntities="true">
			<mapfile-writer file="greece-0.2.4.map" type="ram" map-start-position="37.979166,23.716682" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="romania.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/romania.poly" clipIncompleteEntities="true">
			<mapfile-writer file="romania-0.2.4.map" type="ram" map-start-position="44.437243,26.097679" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="bulgaria.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/bulgaria.poly" clipIncompleteEntities="true">
			<mapfile-writer file="bulgaria-0.2.4.map" type="ram" map-start-position="42.697687,23.321764" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
<!--
  <pipeline name="turkey.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/turkey.poly" clipIncompleteEntities="true">
			<mapfile-writer file="turkey-0.2.4.map" type="ram" map-start-position="41.005358,28.978415" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>
-->
  <pipeline name="lithuania.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/lithuania.poly" clipIncompleteEntities="true">
			<mapfile-writer file="lithuania-0.2.4.map" type="ram" map-start-position="54.690106,25.279799" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="latvia.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/latvia.poly" clipIncompleteEntities="true">
			<mapfile-writer file="latvia-0.2.4.map" type="ram" map-start-position="56.946999,24.105227" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="estonia.map" output-dir="europe">
	<read-pbf file="osm-data/europe.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/europe/estonia.poly" clipIncompleteEntities="true">
			<mapfile-writer file="estonia-0.2.4.map" type="ram" map-start-position="59.437177,24.753227" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

</configuration>

=== bily/mapsforge/mapsforge/src/org/mapsforge/preprocessing/automization/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:configuration osmosis-home="osmosis-home" output-dir="/tmp" workspace="workspace" xmlns:p="http://mapsforge.org/mapsforge-preprocessing-conf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mapsforge.org/mapsforge-preprocessing-conf mapsforge-preprocessing-conf.xsd ">
  <p:pipeline name="test-pipeline">
    <p:read-pbf file="/tmp/planet.osm.pbf">
    	<p:bbox-area-filter name="europe" maxlat="0" minlat="0" maxlon="0" minlon="0">
    		<p:bbox-area-filter name="germany" maxlat="0" minlat="0" maxlon="0" minlon="0">
    			<p:write-pbf file="/tmp/germany.osm.pbf"/>
    		</p:bbox-area-filter>
    		<p:bbox-area-filter name="austria" maxlat="0" minlat="0" maxlon="0" minlon="0">
    			<p:write-pbf file="/tmp/austria.osm.pbf"/>
    		</p:bbox-area-filter>
    	</p:bbox-area-filter>
    	<p:write-pbf file="/tmp/file1"/>
    	<p:write-pbf file="/tmp/file2"/>
    </p:read-pbf>    
  </p:pipeline>
</p:configuration>

=== bily/mapsforge/mapsforge-map-writer-automatization/src/main/config/mapsforge-preprocessing-conf-usa.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration 
	osmosis-home="/export/local-1/public/mapsforge/preprocessing/bin/osmosis-0.39"
	working-dir="/export/local-1/public/mapsforge/preprocessing"
	logging-dir="log" 
	output-dir="output"
	destination-dir="/web/ftp.mapsforge.org/public"
	move="false"  
	xmlns="http://mapsforge.org/mapsforge-preprocessing-conf" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mapsforge.org/mapsforge-preprocessing-conf mapsforge-preprocessing-conf.xsd ">


<!-- MAP FILES -->

  <pipeline name="california.map" output-dir="north-america/us">
	<read-pbf file="osm-data/planet.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/us-west/california.poly" clipIncompleteEntities="true">
			<mapfile-writer file="california-0.2.4.map" type="hd" map-start-position="38.575548,-121.468277" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>

  <pipeline name="new-york.map" output-dir="north-america/us">
	<read-pbf file="osm-data/planet.osm.pbf">
		<polygon-area-filter polygon-file="conf/polygons/geofabrik/us-northeast/new-york.poly" clipIncompleteEntities="true">
			<mapfile-writer file="new-york-0.2.4.map" type="hd" map-start-position="40.715517,-74.007683" md5="true"/>
		</polygon-area-filter>
	</read-pbf>
  </pipeline>



</configuration>
